---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  namespace: test
  labels:
    app: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      initContainers:
      - name: topic-creator
        image: confluentinc/cp-kafka:3.3.0
        command: ["/bin/sh", "-c", "kafka-topics --create --topic person-events-topic --partitions 20 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181"]
      containers:
      - name: registration
        image: adesso/party-service:1.0.0
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service:8081"
        - name: APPLICATION_SERVER
          value: "registration:8080"
        - name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: registration
  namespace: test
spec:
  selector:
    app: registration
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31080
  type: NodePort